package com.axelatc.ei.models;

public enum PermissionEnum {
    LOGOUT,
    READ_DASHBOARD,
    READ_OWN_ACCOUNT,
    EDIT_OWN_ACCOUNT,
    DEACTIVATE_OWN_ACCOUNT,

    NEW_OWN_MEASURES,
    READ_OWN_MEASURES,
    EDIT_OWN_MEASURES,
    DELETE_OWN_MEASURES,

    NEW_USER_ACCOUNTS,
    READ_USER_ACCOUNTS,
    EDIT_USER_ACCOUNTS,
    DEACTIVATE_USER_ACCOUNTS,

    NEW_ROLES,
    READ_ROLES,
    EDIT_ROLES,
    DELETE_ROLES,

    ADD_PERMISSION_ROLES,
    REMOVE_PERMISSION_ROLES,

    READ_PERMISSIONS,

    NEW_MEASURANDS,
    READ_MEASURANDS,
    EDIT_MEASURANDS,
    DELETE_MEASURANDS
}
